[package]
name = "app-user"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
app-core = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
validator = { workspace = true }

[dev-dependencies]
app-testing = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
